### ISSUE TITLE
1.19.2 crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Steveplays28/biome-fog#9]
https://mclo.gs/Q3QDxME

**Comment by Steveplays28** [comment]
Yep, thanks for the report, I'm aware of this issue. I already backported the fix, you can compile it on the 1.19-1.19.2 branch.

Just waiting for it to be reviewed on CF to push the release to all 3 platforms at once.
Didn't expect it to take this long to be reviewed on CF, if CF ends up taking too long I might just manually release.

**Comment by Aces-and-Jacks** [comment]
ah ok. Saw it was added for 1.19.3-1.19.4 so just figured I'd make the issue known if not already

**Comment by Steveplays28** [comment]
All good, I hadn't clarified this anywhere so no worries.

**Comment by Steveplays28** [comment]
Published the backport, you can download it on [Modrinth](https://modrinth.com/mod/biome-fog/version/1.0.1+mc1.19-1.19.2) or [GitHub releases](https://github.com/Steveplays28/biome-fog/releases/tag/v1.0.1%2Bmc1.19-1.19.2).
CF takes extra time to review updates so that will take a bit longer.

Have fun!
